# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: app_development
  password: 123456

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test


production:
  <<: *default
  host: <%= ENV["POSTGRESQL_PORT_5432_TCP_ADDR"] %>
  port: <%= ENV["POSTGRESQL_PORT_5432_TCP_PORT"] %>
  database: <%= ENV["POSTGRESQL_INSTANCE_NAME"] %>
  username: <%= ENV["POSTGRESQL_USERNAME"] %>
  password: <%= ENV["POSTGRESQL_PASSWORD"] %>
